"""Added image_delete_hash colum to recipe table

Revision ID: 45988c6e6283
Revises: b03bff01b8c5
Create Date: 2021-02-06 16:57:07.411634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45988c6e6283'
down_revision = 'b03bff01b8c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image_delete_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'image_delete_hash')
    # ### end Alembic commands ###
